List listWilaya = [
  'Adrar',
  'Aïn-Defla',
  'Aïn-Témouchent',
  'Alger',
  'Annaba',
  'Batna',
  'Béchar',
  'Béjaïa',
  'Biskra',
  'Blida',
  'Bordj-Bou-Arreridj',
  'Bouira',
  'Boumerdès',
  'Chlef',
  'Constantine',
  'Djelfa',
  'El-Bayadh',
  'El-Oued',
  'El-Taref',
  'Ghardaia',
  'Guelma',
  'Illizi',
  'Jijel',
  'Khenchela',
  'Laghouat',
  'M\'Sila',
  'Mascara',
  'Médéa',
  'Mila',
  'Mostaganem',
  'Naâma',
  'Oran',
  'Ouargla',
  'Oum-El-Bouaghi',
  'Relizane',
  'Saida',
  'Sétif',
  'Sidi-Bel-Abbès',
  'Skikda',
  'Souk-Ahras',
  'Tamanrasset',
  'Tébessa',
  'Tiaret',
  'Tindouf',
  'Tipaza',
  'Tissemsilt',
  'Tizi-Ouzou',
  'Tlemcen'
];
List hospitalList = [
  "Hôpital Ibn Sina - Adrar",
  "Hôpital de Timimoun",
  "EPH Frères Saadane - Chlef",
  "Hôpital des Frères Abbas - Ténès",
  "EPH Dr Youcef Djeddi - Laghouat",
  "Hôpital de Aflou",
  "EPH Mohamed Boudiaf - Oum El Bouaghi",
  "Hôpital Mohamed Ben Ghenna - Ain Beida",
  "EPH Ibn Sina - Batna",
  "CHU de Batna",
  "EPH Frantz Fanon - Béjaïa",
  "Hôpital d'Akbou",
  "Hôpital Mohamed Ben Sahraoui - Biskra",
  "Hôpital de Tolga",
  "EPH Dr Tourabi Boudjemaa - Béchar",
  "Hôpital de Taghit",
  "CHU Franz Fanon - Blida",
  "Hôpital de Boufarik",
  "EPH Mohamed Boudiaf - Bouira",
  "Hôpital de Sour El Ghozlane",
  "EPH de Tamanrasset",
  "Hôpital de In Salah",
  "Hôpital Ali Nemmouche - Tébessa",
  "Hôpital de Bir El Ater",
  "CHU Dr Tidjani Damerdji - Tlemcen",
  "Hôpital de Maghnia",
  "EPH Ibn Sina - Tiaret",
  "Hôpital de Frenda",
  "CHU Nedir Mohamed - Tizi Ouzou",
  "Hôpital de Draa Ben Khedda",
  "CHU Mustapha Pacha - Alger",
  "CHU Nafissa Hamoud (ex-Parnet) - Hussein Dey",
  "EPH de Djelfa",
  "Hôpital de Messaad",
  "EPH Mohamed Seddik Benyahia - Jijel",
  "Hôpital de Taher",
  "CHU Saadna Abdennour - Sétif",
  "Hôpital de Ain El Kebira",
  "EPH Ahmed Medeghri - Saïda",
  "Hôpital de El Hassasna",
  "Hôpital Abdelhamid Benbadis - Skikda",
  "Hôpital de Collo",
  "CHU Dr Hassani Abdelkader - Sidi Bel Abbès",
  "Hôpital de Telagh",
  "CHU Ibn Rochd - Annaba",
  "Hôpital de El Hadjar",
  "EPH Dr Bouhadef - Guelma",
  "Hôpital de Bouchegouf",
  "CHU Benbadis - Constantine",
  "Hôpital Mohamed Boudiaf - El Khroub",
  "EPH Ibn Ziri - Médéa",
  "Hôpital de Berrouaghia",
  "EPH Che Guevara - Mostaganem",
  "Hôpital de Ain Tédelès",
  "EPH de M’Sila",
  "Hôpital de Sidi Aissa",
  "EPH de Mascara",
  "Hôpital de Tighennif",
  "CHU Mohamed Boudiaf - Ouargla",
  "Hôpital de Touggourt",
  "CHU d’Oran",
  "EHU 1er Novembre 1954 - Oran",
  "EPH Dr Bouzidi Lakhdar - Bordj Bou Arreridj",
  "Hôpital de Ras El Oued",
  "EPH d’El Tarf",
  "Hôpital de Ben M’hidi",
  "EPH de Tindouf",
  "Hôpital de Tindouf",
];
